import {Dimensions, StyleSheet} from 'react-native';
import colors from '../../utils/colors';
export default StyleSheet.create({
  container: {
    flex: 1,
    color: colors.white,
  },
  header: {
    height: Dimensions.get('screen').height / 12,
    flexDirection: 'row',
    backgroundColor: colors.greyish,
  },
  backbttn: {
    flex: 0.1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backimg: {
    height: '35%',
    tintColor: colors.white,
    resizeMode: 'contain',
    transform: [{rotate: '180deg'}],
  },
  headtxtview: {
    flex: 0.9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headtxt: {
    fontSize: 20,
    color: colors.white,
  },
  ticketview: {
    flex: 1,
    marginHorizontal: 15,
    marginVertical: 10,
    backgroundColor: colors.white,
  },
  nameview: {
    height: Dimensions.get('screen').height / 6,
    borderStyle: 'dashed',
    borderColor: colors.black,
    borderBottomWidth: 1,
    padding: 10,
  },
  lrgtxt: {
    color: colors.black,
    fontSize: 25,
    fontWeight: '600',
  },
  smlltxt: {
    color: colors.black,
    fontSize: 15,
    fontWeight: '400',
  },
  numtickets: {
    position: 'absolute',
    right: 20,
    top: 20,
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
    height: 70,
    width: 70,
  },
  priceview: {
    height: Dimensions.get('screen').height / 4,
    borderColor: colors.black,
    borderBottomWidth: 0.5,
    padding: 10,
  },
  priceviewrow: {
    height: '10%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 10,
  },
  contactview: {
    height: Dimensions.get('screen').height / 7,
    borderColor: colors.black,
    borderBottomWidth: 0.5,
    padding: 10,
  },
  paymentview: {
    height: Dimensions.get('screen').height / 3,
    borderColor: colors.black,
    borderBottomWidth: 0.5,
    padding: 10,
  },
  paymentopt: {
    height: '25%',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    borderBottomWidth: 0.5,
    borderBottomColor: colors.black,
  },
  smllicon: {
    height: 30,
    width: 30,
    tintColor: colors.black,
    alignSelf: 'center',
  },
  contentContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
  },
  optionTab: {
    backgroundColor: colors.white,
    height: 350,
    width: '100%',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    alignSelf: 'center',
    justifyContent: 'space-evenly',
  },
  input: {
    height: 70,
    borderColor: colors.black,
    borderRadius: 10,
    borderWidth: 2,
    width: '95%',
    marginVertical: 15,
    backgroundColor: colors.white,
  },
  selectseatsbttn: {
    height: '100%',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.lightred,
    borderRadius: 10,
  },
  txt: {
    color: colors.white,
    fontSize: 18,
    fontWeight: '500',
  },
});
