import tickets from '../assets/svgs/cinema-ticket.png';
import logosmll from '../assets/pngs/bookmyshow-logo.png';
import BuzzLogo from '../assets/pngs/BuzzLogo.png';
import LiveLogo from '../assets/pngs/LiveLogo.png';
import ProfileLogo from '../assets/pngs/person.png';
import point from '../assets/pngs/Point.png';
import Search from '../assets/pngs/Search.png';
import QrScan from '../assets/pngs/QrScan.png';
import Notification from '../assets/pngs/Notification.png';
import user from '../assets/pngs/user.png';
import Movies from '../assets/pngs/Movies.png';
import Stream from '../assets/pngs/Stream.png';
import Kabbadi from '../assets/pngs/Kabbadi.png';
import Comedy from '../assets/pngs/Comedy.png';
import Sports from '../assets/pngs/Sports.png';
import MusicShow from '../assets/pngs/MusicShows.png';
import Plays from '../assets/pngs/Plays.png';
import Seeall from '../assets/pngs/Seeall.png';
import poster from '../assets/AvatarPoster.jpg';
import poster1 from '../assets/BhediyaPoster.jpg';
import poster2 from '../assets/PantherPoster.jpg';
import bgtheater from '../assets/theater.jpg';
import actor from '../assets/actor.png';
import Comedy1 from '../assets/ComedyShow1.png';
import Comedy2 from '../assets/ComedyShow2.png';
import Music1 from '../assets/MusicShow1.jpg';
import Music2 from '../assets/MusicShow2.jpg';
import newmovie from '../assets/newmovieposter.jpg';
import Comedians from '../assets/Comedians.jpg';
import orders from '../assets/pngs/orders.png';
import creditCard from '../assets/pngs/creditCard.png';
import helpSupport from '../assets/pngs/helpSupport.png';
import settings from '../assets/pngs/settings.png';
import rewards from '../assets/pngs/rewards.png';
import Offers from '../assets/pngs/Offers.png';
import discountStore from '../assets/pngs/discountStore.png';
import giftCard from '../assets/pngs/giftCard.png';
import showTent from '../assets/pngs/showTent.png';
import Share from '../assets/pngs/Share.png';
import Star from '../assets/pngs/Star.png';
export default {
  Movies: Movies,
  newmovie: newmovie,
  Comedians: Comedians,
  bgtheater: bgtheater,
  Share: Share,
  Star: Star,
  poster1: poster1,
  poster2: poster2,
  Stream: Stream,
  poster: poster,
  Music1: Music1,
  Music2: Music2,
  Comedy1: Comedy1,
  Comedy2: Comedy2,
  creditCard: creditCard,
  Kabbadi: Kabbadi,
  Comedy: Comedy,
  Sports: Sports,
  MusicShow: MusicShow,
  Plays: Plays,
  Seeall: Seeall,
  hometab: [
    {key: 1, img: Movies, data: 'Movies'},
    {key: 2, img: Stream, data: 'Stream'},
    {key: 3, img: Kabbadi, data: 'Pro Kabaddi'},
    {key: 4, img: Comedy, data: 'Comedy Shows'},
    {key: 5, img: Sports, data: 'Sports'},
    {key: 6, img: MusicShow, data: 'Music Shows'},
    {key: 7, img: Plays, data: 'Plays'},
    {key: 8, img: Seeall, data: 'See All'},
  ],
  // recommend: [
  //   {key: 1, votes: '8k', stars: '9', img: poster2, name: 'Black Panther'},
  //   {key: 2, votes: '4.4k', stars: '7', img: poster1, name: 'Bhediya'},
  //   {key: 3, votes: '9k', stars: '9.5', img: poster, name: 'Avtaar'},
  //   {key: 4, votes: '8k', stars: '9', img: poster2, name: 'Black Panther'},
  //   {key: 5, votes: '4.4k', stars: '7', img: poster1, name: 'Bhediya'},
  //   {key: 6, votes: '9k', stars: '9.5', img: poster, name: 'Avtaar'},
  // ],
  homeflatlist: {
    Movies: {
      name: 'Recommended Movies',
      data: [
        {
          key: 1,
          votes: '8k',
          stars: '9',
          img: poster2,
          name: 'Black Panther',
          type: 'Movie',
        },
        {
          key: 2,
          votes: '4.4k',
          stars: '7',
          img: poster1,
          name: 'Bhediya',
          type: 'Movie',
        },
        {
          key: 3,
          votes: '9k',
          stars: '9.5',
          img: poster,
          name: 'Avtaar',
          type: 'Movie',
        },
        {
          key: 4,
          votes: '8k',
          stars: '9',
          img: poster2,
          name: 'Black Panther',
          type: 'Movie',
        },
        {
          key: 5,
          votes: '4.4k',
          stars: '7',
          img: poster1,
          name: 'Bhediya',
          type: 'Movie',
        },
        {
          key: 6,
          votes: '9k',
          stars: '9.5',
          img: poster,
          name: 'Avtaar',
          type: 'Movie',
        },
      ],
    },
    Event: {
      name: 'Event Near You',
      data: [
        {key: 1, votes: '8k', stars: '9', img: poster2, name: 'Black Panther'},
        {key: 2, votes: '4.4k', stars: '7', img: poster1, name: 'Bhediya'},
        {key: 3, votes: '9k', stars: '9.5', img: poster, name: 'Avtaar'},
        {key: 4, votes: '8k', stars: '9', img: poster2, name: 'Black Panther'},
        {key: 5, votes: '4.4k', stars: '7', img: poster1, name: 'Bhediya'},
        {key: 6, votes: '9k', stars: '9.5', img: poster, name: 'Avtaar'},
      ],
    },
  },
  liveflatlist: {
    Music: {
      name: 'Top Music Shows',
      data: [
        {
          key: 1,
          votes: '8k',
          stars: '9',
          img: Music1,
          name: 'Arijit Live in Ahmedabad',
          loc: 'Lavish Green Ahmedabad',
          price: '$233',
          type: 'Event',
          act: 'Music Concert',
          time: '12 Dec 2022 at 7:00 PM',
          duration: '5hrs',
          lang: 'Hindi',
          age: '12+ yrs',
          artist: [{key: 1, img: ProfileLogo, name: 'Arijit'}],
        },
        {
          key: 2,
          votes: '8k',
          stars: '9',
          img: Music2,
          name: 'Live NewYear with Darshan Raval',
          loc: 'Venue to be anounced',
          price: '$233',
          type: 'Event',
          act: 'Music Concert',
          time: '31 Dec 2022 at 7:00 PM',
          duration: '6hrs',
          lang: 'Hindi,Gujarati',
          age: '12+ yrs',
          artist: [{key: 1, img: ProfileLogo, name: 'Darshan Raval'}],
        },
        {
          key: 3,
          votes: '8k',
          stars: '9',
          img: Music1,
          name: 'Arijit Live in Ahmedabad',
          loc: 'Lavish Green Ahmedabad',
          price: '$233',
          type: 'Event',
          act: 'Music Concert',
          time: '12 Dec 2022 at 7:00 PM',
          duration: '5hrs',
          lang: 'Hindi',
          age: '12+ yrs',
          artist: [{key: 1, img: ProfileLogo, name: 'Arijit'}],
        },
        {
          key: 4,
          votes: '8k',
          stars: '9',
          img: Music2,
          name: 'Live NewYear with Darshan Raval',
          loc: 'Venue to be anounced',
          price: '$233',
          type: 'Event',
          act: 'Music Concert',
          time: '31 Dec 2022 at 7:00 PM',
          duration: '6hrs',
          lang: 'Hindi,Gujarati',
          age: '12+ yrs',
          artist: [{key: 1, img: ProfileLogo, name: 'Darshan Raval'}],
        },
        {
          key: 5,
          votes: '8k',
          stars: '9',
          img: Music2,
          name: 'Live NewYear with Darshan Raval',
          loc: 'Venue to be anounced',
          price: '$233',
          type: 'Event',
          act: 'Music Concert',
          time: '31 Dec 2022 at 7:00 PM',
          duration: '6hrs',
          lang: 'Hindi,Gujarati',
          age: '12+ yrs',
          artist: [{key: 1, img: ProfileLogo, name: 'Darshan Raval'}],
        },
        {
          key: 6,
          votes: '8k',
          stars: '9',
          img: Music1,
          name: 'Arijit Live in Ahmedabad',
          loc: 'Lavish Green Ahmedabad',
          price: '$233',
          type: 'Event',
          act: 'Music Concert',
          time: '12 Dec 2022 at 7:00 PM',
          duration: '5hrs',
          lang: 'Hindi',
          age: '12+ yrs',
          artist: [{key: 1, img: ProfileLogo, name: 'Arijit'}],
        },
      ],
    },
    Comedy: {
      name: 'Top Comedy Shows',
      data: [
        {
          key: 1,
          votes: '8k',
          stars: '9',
          img: Comedy1,
          name: 'Jo Bolta HAi Wahi Hota Hai by Harsh Gujral',
          loc: 'HK HAll:Ahmedabad',
          price: '$233',
          type: 'Event',
          act: 'Comedy Show',
          time: '31 Dec 2022 at 9:00 PM',
          duration: '2hrs',
          lang: 'English,Hindi',
          age: '16+ yrs',
          artist: [{key: 1, img: ProfileLogo, name: 'Harsh Gujral'}],
        },
        {
          key: 2,
          votes: '8k',
          stars: '9',
          img: Comedy2,
          name: 'The Rahul Dua Show',
          loc: 'HK HAll:Ahmedabad',
          price: '$233',
          type: 'Event',
          act: 'Comedy Show',
          time: '14 Nov 2022 at 7:00 PM',
          duration: '1hr',
          lang: 'Hindi',
          age: '18+ yrs',
          artist: [{key: 1, img: ProfileLogo, name: 'Rahul Dua'}],
        },
        {
          key: 3,
          votes: '8k',
          stars: '9',
          img: Comedy1,
          name: 'Jo Bolta HAi Wahi Hota Hai by Harsh Gujral',
          loc: 'HK HAll:Ahmedabad',
          price: '$233',
          type: 'Event',
          act: 'Comedy Show',
          time: '31 Dec 2022 at 9:00 PM',
          duration: '2hrs',
          lang: 'English,Hindi',
          age: '16+ yrs',
          artist: [{key: 1, img: ProfileLogo, name: 'Harsh Gujral'}],
        },
        {
          key: 4,
          votes: '8k',
          stars: '9',
          img: Comedy2,
          name: 'The Rahul Dua Show',
          loc: 'HK HAll:Ahmedabad',
          price: '$233',
          type: 'Event',
          act: 'Comedy Show',
          time: '14 Nov 2022 at 7:00 PM',
          duration: '1hr',
          lang: 'Hindi',
          age: '18+ yrs',
          artist: [{key: 1, img: ProfileLogo, name: 'Rahul Dua'}],
        },
        {
          key: 5,
          votes: '8k',
          stars: '9',
          img: Comedy1,
          name: 'Jo Bolta HAi Wahi Hota Hai by Harsh Gujral',
          loc: 'HK HAll:Ahmedabad',
          price: '$233',
          type: 'Event',
          act: 'Comedy Show',
          time: '31 Dec 2022 at 9:00 PM',
          duration: '2hrs',
          lang: 'English,Hindi',
          age: '16+ yrs',
          artist: [{key: 1, img: ProfileLogo, name: 'Harsh Gujral'}],
        },
        {
          key: 6,
          votes: '8k',
          stars: '9',
          img: Comedy2,
          name: 'The Rahul Dua Show',
          loc: 'HK HAll:Ahmedabad',
          price: '$233',
          type: 'Event',
          act: 'Comedy Show',
          time: '14 Nov 2022 at 7:00 PM',
          duration: '1hr',
          lang: 'Hindi',
          age: '18+ yrs',
          artist: [{key: 1, img: ProfileLogo, name: 'Rahul Dua'}],
        },
      ],
    },
  },
  livecarousel: [
    {key: 1, img: Comedy2},
    {key: 2, img: Music2},
    {key: 3, img: Music1},
    {key: 4, img: Comedy1},
  ],
  optiondata: [
    {
      key: 1,
      name: 'Your Order',
      about: 'View all your bookings & Purchase',
      img: orders,
      locked: false,
    },
    {
      key: 2,
      name: 'Stream Library',
      about: 'Rented & Purchased Movies',
      img: Stream,
      locked: false,
    },
    {
      key: 3,
      name: 'Play Credit Card',
      about: 'View your Play Credit Card details and offers',
      img: creditCard,
      locked: false,
    },
    {
      key: 4,
      name: 'Help & Support',
      about: 'View commonly asked quries and Chat',
      img: helpSupport,
      locked: false,
    },
    {
      key: 5,
      name: 'Account & Settings',
      about: 'Location,Payments,Permissions & More',
      img: settings,
      locked: false,
    },
  ],
  optiondata2: [
    {
      key: 1,
      name: 'Rewards',
      about: 'View all your Rewards & unlock new one',
      img: rewards,
      locked: false,
    },
    {
      key: 2,
      name: 'Offers',
      about: '',
      img: Offers,
      locked: false,
    },
    {
      key: 3,
      name: 'Discount Store',
      about: '',
      img: discountStore,
      locked: false,
    },
    {
      key: 4,
      name: 'Gift Cards',
      about: '',
      img: giftCard,
      locked: false,
    },
    {
      key: 5,
      name: 'List Your Shows',
      about: 'Got an event? Partner with us',
      img: showTent,
      locked: false,
    },
  ],
  tickets: tickets,
  Search: Search,
  Notification: Notification,
  QrScan: QrScan,
  user: user,
  BuzzLogo: BuzzLogo,
  LiveLogo: LiveLogo,
  ProfileLogo: ProfileLogo,
  pointimg: point,
  logosmll: logosmll,
  data: [
    {
      key: 1,
      img: tickets,
      data: 'Buy tickets online from BookMyShow',
    },
    {
      key: 2,
      img: tickets,
      data: 'Buy tickets online from BookMyShow',
    },
    {
      key: 3,
      img: tickets,
      data: 'Buy tickets online from BookMyShow',
    },
  ],
  livefl: [
    {key: 1, img: actor, name: 'Plays'},
    {key: 2, img: actor, name: 'Comedy Shows'},
    {key: 3, img: actor, name: 'Amusment Park'},
    {key: 4, img: actor, name: 'Sports'},
    {key: 5, img: actor, name: 'Workshop'},
  ],
  Moviesdata: [
    {
      key: 1,
      type: 'Movie',
      votes: '8k',
      stars: '9',
      types: '2D, 3D, IMAX 3D, 4DX 3D',
      lang: 'English, Hindi, Tamil, Malayalam',
      img: poster2,
      name: 'Black Panther',
      abt: '3h 12m - Action,Adventure,Fantasy - UA - 16 Dec,2022',
      description:
        'A great Movie with good story line and best cgi. Story of a species from a different planet.Continued from the 1st part of the movie where they discover new city under water',
    },
    {
      key: 2,
      type: 'Movie',
      votes: '4.4k',
      stars: '7',
      types: '2D, 3D, IMAX 3D',
      lang: 'Hindi, Tamil, Malayalam',
      img: poster1,
      name: 'Bhediya',
      abt: '3h 12m - Action,Adventure,Fantasy - UA - 16 Dec,2022',
      description:
        'A great Movie with good story line and best cgi. Story of a species from a different planet.Continued from the 1st part of the movie where they discover new city under water',
    },
    {
      key: 3,
      type: 'Movie',
      votes: '9k',
      stars: '9.5',
      types: '2D, 3D, IMAX 3D, 4DX 3D',
      lang: 'English, Hindi, Tamil, Malayalam',
      img: poster,
      name: 'Avtaar',
      abt: '3h 12m - Action,Adventure,Fantasy - UA - 16 Dec,2022',
      description:
        'A great Movie with good story line and best cgi. Story of a species from a different planet.Continued from the 1st part of the movie where they discover new city under water',
    },
    {
      key: 4,
      type: 'Movie',
      votes: '8k',
      stars: '9',
      types: '2D, 3D, IMAX 3D, 4DX 3D',
      lang: 'English, Hindi, Tamil, Malayalam',
      img: poster2,
      name: 'Black Panther',
      abt: '3h 12m - Action,Adventure,Fantasy - UA - 16 Dec,2022',
      description:
        'A great Movie with good story line and best cgi. Story of a species from a different planet.Continued from the 1st part of the movie where they discover new city under water',
    },
    {
      key: 5,
      type: 'Movie',
      votes: '4.4k',
      stars: '7',
      types: '2D, 3D, IMAX 3D',
      lang: 'Hindi, Tamil, Malayalam',
      img: poster1,
      name: 'Bhediya',
      abt: '3h 12m - Action,Adventure,Fantasy - UA - 16 Dec,2022',
      description:
        'A great Movie with good story line and best cgi. Story of a species from a different planet.Continued from the 1st part of the movie where they discover new city under water',
    },
    {
      key: 6,
      type: 'Movie',
      votes: '9k',
      stars: '9.5',
      types: '2D, 3D, IMAX 3D, 4DX 3D',
      lang: 'English, Hindi, Tamil, Malayalam',
      img: poster,
      name: 'Avtaar',
      abt: '3h 12m - Action,Adventure,Fantasy - UA - 16 Dec,2022',
      description:
        'A great Movie with good story line and best cgi. Story of a species from a different planet.Continued from the 1st part of the movie where they discover new city under water',
    },
  ],
};
